-- loop until RETURN_QUIT code is sent

RETURN_GAME_LAUNCH = 0
RETURN_GAME_END = 1
RETURN_GAME_PAUSE = 2
RETURN_GAME_UNPAUSE = 3
RETURN_GAME_CREDITS = 4
RETURN_GAME_ESCAPE = 5
RETURN_GUI_PROMPT = 6
RETURN_TIMEDEMO = 7
RETURN_TIMEDEMO_ABORT = 8
RETURN_CREDITS = 9
RETURN_QUIT = 10

-- SetCallback("gui")
-- SystemMainLoop()

SetCallback("timedemo")
SystemMainLoop()
